export const AUTH_INIT = 'AUTH_INIT'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export const LOGOUT = 'LOGOUT'

export const SET_FAVORITE_ADS = 'SET_FAVORITE_ADS'
export const FETCH_FAVORITE_ADS_FAILURE = 'FETCH_FAVORITE_ADS_FAILURE'

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES'

export const START_LOADING_PAGE = 'START_LOADING_PAGE'
export const STOP_LOADING_PAGE = 'STOP_LOADING_PAGE'
